
on: push

jobs:
  myjob:
    runs-on: 'windows-2019'
    steps:
      - shell: bash
        env:
          MSYS: winsymlinks:nativestrict
        run: |
          mkdir artifact
          mkdir artifact/aaa
          touch artifact/aaa/bbb.txt

          mkdir kkk
          touch kkk/lll.txt

          ln -s "$(pwd)/kkk" artifact/kkk_symlink

          mkdir artifact/kkk_phys
          ln "$(pwd)/kkk/lll.txt" artifact/kkk_phys/lll_hardlink.txt
      
      - uses: actions/upload-artifact@v2
        with:
          name: myartifact
          path: artifact/
